services:
  api:
    build:
      context: .
    container_name: "rag-with-qdrant"
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - vector-db
  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - vector_db_data:/qdrant/storage
    restart: always

volumes:
  vector_db_data:
    driver: local
