services:
  api:
    build:
      context: .
    container_name: "rag-with-qdrant"
    environment:
      PORT: 8000
      OLLAMA_BASE_URL: http://ollama:11434
      GROQ_API_KEY: ${GROQ_API_KEY}
      COLLECTION_NAME: ${COLLECTION_NAME}
      VOYAGE_AI_SECRET_KEY: ${VOYAGE_AI_SECRET_KEY}
      QDRANT_URL: ${QDRANT_URL}
    ports:
      - "8000:8000"
    depends_on:
      - vector-db

  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - vector_db_data:/qdrant/storage
    restart: always

volumes:
  vector_db_data:
