services:
  api:
    build:
      context: .
    container_name: "rag-with-qdrant"
    environment:
      PORT: ${PORT}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      GROQ_API_KEY: ${GROQ_API_KEY}
      COLLECTION_NAME: ${COLLECTION_NAME}
      QDRANT_URL: ${QDRANT_URL}
    ports:
      - "${PORT}:${PORT}"
